require "user.autocmds"
require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.transparent"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.dashboard"
require "user.comment"
require "user.gitsigns"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
--vim.notify = require('notify')
require "user.colorozer"
--vim.cmd('TransparentEnable')
--require "user.lsp_lines"
